services:
  docshub:
    container_name: docshub
    image: atmgrupomaggioli/docshub:latest
    ports:
      - "4321:4321"
    restart: unless-stopped
    volumes:
      - ./docs:/app/src/docs
      - ./images:/app/public/images
    environment:
      DOCUMENTATION_TITLE: "Standard Documentation"
      VERSION: "0.0.1"
      REPOSITORY_TYPE: "github"
      REPOSITORY_URL: "https://github.com/atmgrupomaggioli/docshub"
    profiles:
      - standard

  docshub-interactive:
    container_name: docshub-interactive
    image: atmgrupomaggioli/docshub:interactive
    ports:
      - "4321:4321"
    restart: unless-stopped
    volumes:
      - ./docs:/app/src/docs
      - ./images:/app/public/images
    environment:
      DOCUMENTATION_TITLE: "Interactive Documentation"
      VERSION: "0.0.1"
      REPOSITORY_TYPE: "github"
      REPOSITORY_URL: "https://github.com/atmgrupomaggioli/docshub"
    profiles:
      - interactive