name: ⚙️ New Issue
description: Create a new issue for a bug or feature.
title: "🔔 New Issue"
labels: ["new", "request"]
body:
  - type: dropdown
    id: project-type
    attributes:
      label: Project Type
      description: Enter the project type.
      options:
        - DocsHub CLI
        - DocsHub Docs (Astro)
        - All
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Describe the issue here
      placeholder: Describe the issue.
    validations:
      required: true
  - type: input
    id: docshub-version
    attributes:
      label: Docshub Version
      description: Enter the version of Docshub you are using.
      placeholder: "v2.0.0"
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: Operating System
      description: Enter the operating system you are using.
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Web Browser
      description: Enter the browser you are using.
      options:
        - Chrome
        - Brave
        - Opera
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true
  - type: dropdown
    id: node-version
    attributes:
      label: Node Version
      description: Enter the node version you are using.
      options:
        - "22"
        - "21"
        - "20"
        - "19"
        - "18"
    validations:
      required: true
  - type: dropdown
    id: deploy-platform
    attributes:
      label: Deployed on
      description: Enter the platform you are using.
      options:
        - Docker (Docshub CLI Interactive Mode)
        - Docker (Docshub CLI Standard Mode)
        - Vercel Adapter (@astrojs/vercel)
    validations:
      required: true
  - type: markdown
    id: additional-info
    attributes:
      value: |
        **Additional Info**  
        You can add any extra details, logs, screenshots, or context below.
